### PR TITLE
Splunk Logging Driver: raw format

### PR DESCRIPTION
**Pull request by outcoldman**
DO NOT MERGE, FOR INTERNAL CODE REVIEW!

In version 6.4 Http Event Collector added support for incoming raw
format. Use can specify with `splunk-format=json|raw` which format he
wants to use when sending events to Splunk.
Raw format prepends `tag` and `attrs` to each message, like
`627710de10d7 test=foo message`.

In this change I also added option to skip verification for Splunk url
with `splunk-verifyconnection=true|false`.

### CODE REVIEW

**Comment by glennblock** [comment]
LGTM. What real benefit do you see for adding raw? Timestamp extraction? Smaller payload?

**Comment by glennblock** [comment]
@outcoldman one other change you might consider for 6.4 is we allow metadata to be passed in the querystring. So you can have a url of services/raw?source=foo&sourcetype=bar.

**Comment by glennblock** [comment]
Never mind, I see now you already handled the metadata for raw.

**Comment by glennblock** [comment]
Great to see you added disabling the network verification :+1:

**Comment by outcoldman** [comment]
Fields extraction will be the main benefit

Thanks,
Den (from my phone)

On Thu, Jun 9, 2016 at 9:51 PM -0700, "Glenn Block" <notifications@github.com<mailto:notifications@github.com>> wrote:

LGTM. What real benefit do you see for adding raw? Timestamp extraction? Smaller payload?

##

**Comment by glennblock** [comment]
Only diff is timestamp and breaking rules. JSON field extraction still
doesn't work. Regex extractions work with the standard protocol.

**Comment by outcoldman** [comment]
Declined because of  https://github.com/splunk/docker/pull/3

**Pull request closed without merging**
