### PR TITLE
Adding splunk-data-* option for specifying additional data. This was …

### PR DESCRIPTION
**Pull request by glennblock**
…requested by @phylake

### CODE REVIEW

**Comment by glennblock** [comment]
Hey @phylake can you take a look at this and see if it is what you were thinking? The `data` field in the image below is populated with keys that were configured via the log driver in my fork using the `splunk-data-*` option. By convention whatever is after `splunk-data` becomes the key.

```
docker run --log-driver=splunk --log-opt splunk-token=CD8F24E8-D96F-47FF-AF80-9A768441F4EC --log-opt splunk-url=https://10.0.1.15:8088 --log-opt splunk-insecureskipverify=true --log-opt splunk-data-foo="bar" --log-opt splunk-data-bar="baz" hello-world 
```

screen shot 2015-10-11 at 2 47 48 am

**Comment by halr9000** [comment]
Maybe eat the dash? I see "-foo" is the resulting field name.

**Comment by glennblock** [comment]
@halr9000 good catch! I was wondering about that, but it was late. I'll fix it.

**Comment by glennblock** [comment]
@halr9000 fixed.

screen shot 2015-10-11 at 10 26 02 am

**Comment by glennblock** [comment]
What does everyone think about the convention based approach on the option? Alternative would be some fixed option and you specify key/value explicitly like `--log-opt splunk-data="foo:bar"`. Is a convention like this acceptable in the go world? The other advantage is it allows cleanly specifying multiple kvps cleanly as each is a separate option.

**Comment by halr9000** [comment]
I like it as-is @gblock. An alternative might look like Docker inspect syntax, which I really hate, by that's just me. Example: https://docs.docker.com/reference/commandline/inspect/#examples

**Comment by glennblock** [comment]
Yeah not a fan of that either. I had the idea of a JSON object pop into my
head, but I quickly ejected it :-)

**Comment by phylake** [comment]
@glennblock That's workable but not pretty. I don't like the implicit key `splunk-data-{KEY}`. I like the single key-value `--log-opt splunk-data="key=value,key2=value2"`.

So this is fine for static values that want to be added at container start time (and happens to satisfy my use case), but it doesn't help with values that may change over time. I could see all sort of interesting uses for a generic hook into logs that were sent into splunk. I don't know if a `.git/hooks` style hook or a webhook would be more appropriate. One powerful use case would be to filter out PII from logs. For a platform that takes care of deploying splunk on behalf of services that use it, the ability to capture a log before it was sent to splunk

**Comment by phylake** [comment]
@glennblock That's workable but not pretty. I don't like the implicit key `splunk-data-{KEY}`. I like the single key-value `--log-opt splunk-data="key=value,key2=value2"` as you said.

So this is fine for static values that want to be added at container start time (and happens to satisfy my immediate use case), but it doesn't help with values that may change over time. I could see all sort of interesting uses for a generic hook into logs that were about to be sent into splunk. I don't know if a `.git/hooks` style hook or a webhook would be more appropriate.

One powerful use case would be to filter out PII from logs. Another is for blue/green deployments - I'd add to the log a key-value pair denoting the color being demoted so I could easily correlate the demotion with other types of errors that might occur. For example if things aren't being demoted properly there might be all sort of spurious network errors and I could track down that the errors were related to the demotion. It's the kind of thing that could be the difference between quickly find/fixing a bug or letting it go on forever because the service my platform deploys doesn't know it's being deployed, and the errors don't occur at my layer in the stack.

What do you think? I'm not sure what the lifecycle/hook name would be but I was thinking something like `--log-opt splunk-hook=http://localhost:9000/splunk/tag_deployment` or `--log-opt splunk-hook=/usr/local/bin/splunk_tag_deployment` where the HTTP response would be used in the first, and STDOUT in the second.

The great thing about generic hooks is there are all sorts of use cases you probably can't imagine but would add immense value to splunk.

**Comment by glennblock** [comment]
@phyake OK on the single key, I can make that work. Thanks!

As to values over the time, that is beyond the scope of this work. It also feels like if such support were added, that would be a general purpose docker feature for log-drivers not a one-off. I'd suggest filing an issue in the Docker repo to discuss your design proposal. 

One could argue even that this static feature should be something general purpose that other log drivers should be able to leverage, but I think it is reasonable to add it first here and then if others want it, then maybe it gets elevated to a general feature. 

I am not a huge fan of the driver depending on a URL which it would continually poll. An alternative would be some sort of API that you can invoke to change the metadata, OR have a local config file that is automatically re-loaded whenever it changes.

Thanks!

**Comment by glennblock** [comment]
Allright so I'll go with this syntax `--log-opt splunk-data="foo=bar,bar=baz"`. That's  more compact.

**Comment by halr9000** [comment]
@phylake I'm thinking your anonymize use case can be handled well out of band, meaning in Splunk, not in Docker. This page outlines the ways this can be accomplished: [Getting Data In - Anonymize data](http://docs.splunk.com/Documentation/Splunk/latest/Data/Anonymizedata). There are some caveats listed on this page which _may_ apply to the Event Collector however, which might prove troublesome. I've pinged our dev & docs team for clarification and will report back what I find. May take a few days unless I can find the time to test it.

**Comment by halr9000** [comment]
Also @phylake I can think of other ways to accomplish your blue/green use case, which is a great one, by the way. Honestly, I would just record promotions _anywhere_, and as long as Splunk is picking up that "change event", you can perform your correlations at search-time using the search processing language. It's hard to come up with a specific example, but let's pseudocode it:

e.g. CI or automation tool logs an event such as:

```
2015-10-12 07:37:12Z+500 [myapp1/instanceid1] environment promoted to production
2015-10-12 07:37:13Z+500 [myapp1/instanceid2] environment promoted to production
```

One would use basic Splunk features for field extraction to turn `[myapps/instanceid1]` into fields, [documented here](http://docs.splunk.com/Documentation/Splunk/latest/Search/Extractfieldswithsearchcommands).

And this might correspond with a Docker run such as (abbreviated):
`docker run --log-driver=splunk --log-opt splunk-data="appname=myapp1,instance=instanceid2" hello-world`

Then at search-time in SPL, a simple search like `appname=myapp1` would show promotion events in line with log data from containers invoked accordingly.

This is just a simple example of course.

Edit: and hey, if you like the web/commit hook style of integration, we have options!
- have hook script > to a file, and have Splunk monitor that file
- go straight to the [Event Collector](http://docs.splunk.com/Documentation/Splunk/latest/Data/UsetheHTTPEventCollector), which is the same feature this logging driver uses. A quick curl could insert the promotion event.

**Pull request closed without merging**
